server {
    listen 80;
    # 用 _ 表示匹配所有请求（IP 访问 + 任意域名）
    # 之后加了子域名 report.xxx.com 也不用改这里
    server_name _;

    client_max_body_size 50M;

    proxy_read_timeout 600s;
    proxy_connect_timeout 600s;

    location / {
        proxy_pass http://unix:/tmp/y4_report.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
